[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
files = ["chzzk/chzzk.py"]
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true
